<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Http"/>
        <PackageReference Include="Scrutor"/>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Common/CurrencyAliases.json" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Banguat.ExchangeRates.Tests"/>
    </ItemGroup>

</Project>
